### ISSUE TITLE
分红送股份额显示异常

### ISSUE THREAD

**Issue by weepo-bean** [zillionare/backtesting#19]
如下：2020-07-03查询持有‘600345.XSHG’股票32600手：
![图片](https://user-images.githubusercontent.com/57930570/183799115-43b03f96-3750-462f-a065-7136b09b72a1.png)

当天下单全部卖出，返回的成交信息中，'filled'字段显示全部成交：
![图片](https://user-images.githubusercontent.com/57930570/183799768-6e0d3711-61be-41bf-a4f8-856cfb3db527.png)

2020-07-17日查询仓位时，显示该股及仓位中其他股票有分红份额：
![图片](https://user-images.githubusercontent.com/57930570/183799254-40b85333-0252-43bf-a1b5-59ddc8df4d52.png)

再次对这三只股票下单卖出的时候，显示没有持仓：
![图片](https://user-images.githubusercontent.com/57930570/183799339-7d775a25-00e7-4ff9-be0d-ac9c541f64b8.png)

**Comment by zillionare** [comment]
should be fixed before 0.4.8, please check.
