### ISSUE TITLE
get_assets中start参数bug

### ISSUE THREAD

**Issue by weepo-bean** [zillionare/backtesting#25]
在调用get_assets时，如果start为回测中的第一个交易日，可以正常返回，但是当start设置为中间其他的交易日时，报错，不设置start时不报错。代码和报错信息为：
client.get_assets(start=arrow.get(‘2020-10-09’).date(), end=arrow.get(‘2020-10-10’).date())

TradeError: operands could not be broadcast together with shapes (2,) (0,) : (499, 'operands could not be broadcast together with shapes (2,) (0,) ')

**Comment by zillionare** [comment]
fixed in 0b2a913d4ae6047f95fc11b439910157b54a2864
